apiVersion: v1
kind: Service
metadata:
  name: {{ include "quakewatch-helm.fullname" . }}
  labels:
    {{- include "quakewatch-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "quakewatch-helm.selectorLabels" . | nindent 4 }}
